// Tabular Editor 2 script — generated by src/step5_generate_dax.py
// Generated 2026-09-10
// Coefficients from analysis_model_results.csv, model M2 distance weighted, n=137
//
// Usage: open your .pbix in Power BI Desktop, launch Tabular Editor
// from External Tools, open this file, press F5, then File > Save.
// Rerunning updates existing measures rather than duplicating them.

var tbl = Model.Tables.FirstOrDefault(t => t.Name == "_Measures");
if (tbl == null) {
    Error("Measure table not found. In Power BI Desktop run: _Measures = { BLANK() }");
    return;
}

int created = 0, updated = 0;

// ---- Severity Coefficient ----
{
    var name = @"Severity Coefficient";
    var expr = @"-1.6620";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"00 Constants";
    m.Description = @"Regression coefficient on proximity-weighted severity. Source: analysis_model_results.csv, model M2 distance weighted, n=137";
    m.FormatString = @"0.0000";
}

// ---- Severity CI Low ----
{
    var name = @"Severity CI Low";
    var expr = @"-2.4148";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"00 Constants";
    m.Description = @"Lower bound of the 95% confidence interval.";
    m.FormatString = @"0.0000";
}

// ---- Severity CI High ----
{
    var name = @"Severity CI High";
    var expr = @"-0.9091";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"00 Constants";
    m.Description = @"Upper bound of the 95% confidence interval.";
    m.FormatString = @"0.0000";
}

// ---- AUD per USD ----
{
    var name = @"AUD per USD";
    var expr = @"0.65";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"00 Constants";
    m.Description = @"Exchange rate assumption, used only to express tonnes as dollars.";
    m.FormatString = @"0.00";
}

// ---- Proximity Decay Km ----
{
    var name = @"Proximity Decay Km";
    var expr = @"200";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"00 Constants";
    m.Description = @"Distance scale for the severity weighting. An assumption.";
    m.FormatString = @"0";
}

// ---- Availability Target ----
{
    var name = @"Availability Target";
    var expr = @"0.98";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"00 Constants";
    m.Description = @"Illustrative benchmark. Not sourced from Pilbara Ports.";
    m.FormatString = @"0.0%";
}

// ---- Total Downtime Days ----
{
    var name = @"Total Downtime Days";
    var expr = @"SUM ( fact_reliability_event[event_downtime_days] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"01 Reliability";
    m.Description = @"Estimated production-equivalent lost days across cyclone events.";
    m.FormatString = @"#,0.0";
}

// ---- Total Downtime Hours ----
{
    var name = @"Total Downtime Hours";
    var expr = @"SUM ( fact_reliability_event[event_downtime_hours] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"01 Reliability";
    m.Description = @"Downtime expressed in hours.";
    m.FormatString = @"#,0";
}

// ---- Total Lost Mt ----
{
    var name = @"Total Lost Mt";
    var expr = @"SUM ( fact_reliability_event[event_lost_mt] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"01 Reliability";
    m.Description = @"Estimated production lost to cyclone events, million tonnes.";
    m.FormatString = @"#,0.0";
}

// ---- Event Count ----
{
    var name = @"Event Count";
    var expr = @"COUNTROWS ( fact_reliability_event )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"01 Reliability";
    m.Description = @"Number of cyclone events in context.";
    m.FormatString = @"#,0";
}

// ---- Severe Event Count ----
{
    var name = @"Severe Event Count";
    var expr = @"CALCULATE ( [Event Count], fact_reliability_event[category] >= 3 )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"01 Reliability";
    m.Description = @"Category 3 and above events.";
    m.FormatString = @"#,0";
}

// ---- Observation Years ----
{
    var name = @"Observation Years";
    var expr = @"DIVIDE ( DISTINCTCOUNT ( fact_reliability_monthly[month] ), 12 )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"01 Reliability";
    m.Description = @"Observation window in years.";
    m.FormatString = @"#,0.0";
}

// ---- Downtime Days Per Year ----
{
    var name = @"Downtime Days Per Year";
    var expr = @"DIVIDE ( [Total Downtime Days], [Observation Years] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"01 Reliability";
    m.Description = @"Annualised downtime.";
    m.FormatString = @"#,0.0";
}

// ---- Lost Mt Per Year ----
{
    var name = @"Lost Mt Per Year";
    var expr = @"DIVIDE ( [Total Lost Mt], [Observation Years] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"01 Reliability";
    m.Description = @"Annualised production loss.";
    m.FormatString = @"#,0.0";
}

// ---- Availability Pct ----
{
    var name = @"Availability Pct";
    var expr = @"AVERAGE ( fact_reliability_monthly[availability] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"01 Reliability";
    m.Description = @"Mean monthly availability against modelled no-cyclone capability.";
    m.FormatString = @"0.00%";
}

// ---- Weather Availability Pct ----
{
    var name = @"Weather Availability Pct";
    var expr = @"CALCULATE ( [Availability Pct], fact_reliability_monthly[weighted_severity] > 0 )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"01 Reliability";
    m.Description = @"Availability restricted to months with a cyclone. Headline figure.";
    m.FormatString = @"0.00%";
}

// ---- Overall Weather Availability ----
{
    var name = @"Overall Weather Availability";
    var expr = @"1 - DIVIDE ( [Total Downtime Days], [Observation Years] * 365.25 )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"01 Reliability";
    m.Description = @"Availability across the whole period. Higher than the weather-month figure because the denominator differs. Show it as supporting text, not as a second headline, or readers will assume an error.";
    m.FormatString = @"0.00%";
}

// ---- Months Below Target ----
{
    var name = @"Months Below Target";
    var expr = @"CALCULATE ( COUNTROWS ( fact_reliability_monthly ), fact_reliability_monthly[availability] < [Availability Target] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"01 Reliability";
    m.Description = @"Months falling short of the target.";
    m.FormatString = @"#,0";
}

// ---- MTBF Days ----
{
    var name = @"MTBF Days";
    var expr = @"AVERAGE ( fact_reliability_event[days_since_previous] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"02 MTBF and MTTR";
    m.Description = @"Mean days between consecutive events, all severities. Pulled down by tropical lows, so pair it with the severe-only figure.";
    m.FormatString = @"#,0";
}

// ---- MTBF Years ----
{
    var name = @"MTBF Years";
    var expr = @"DIVIDE ( [MTBF Days], 365.25 )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"02 MTBF and MTTR";
    m.Description = @"MTBF expressed in years.";
    m.FormatString = @"#,0.00";
}

// ---- MTBF Severe Days ----
{
    var name = @"MTBF Severe Days";
    var expr = @"VAR Severe =
    FILTER (
        ALLSELECTED ( fact_reliability_event ),
        fact_reliability_event[category] >= 3
    )
VAR N = COUNTROWS ( Severe )
VAR FirstDate = MINX ( Severe, fact_reliability_event[peak_datetime] )
VAR LastDate = MAXX ( Severe, fact_reliability_event[peak_datetime] )
RETURN
    IF ( N > 1, DIVIDE ( DATEDIFF ( FirstDate, LastDate, DAY ), N - 1 ) )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"02 MTBF and MTTR";
    m.Description = @"MTBF for Category 3 and above only. The planning-relevant figure.";
    m.FormatString = @"#,0";
}

// ---- MTTR Days ----
{
    var name = @"MTTR Days";
    var expr = @"AVERAGE ( fact_reliability_event[event_downtime_days] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"02 MTBF and MTTR";
    m.Description = @"Mean days to restore normal throughput. Inferred from monthly tonnage, not a measured repair duration.";
    m.FormatString = @"#,0.00";
}

// ---- MTTR Severe Days ----
{
    var name = @"MTTR Severe Days";
    var expr = @"CALCULATE ( [MTTR Days], fact_reliability_event[category] >= 3 )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"02 MTBF and MTTR";
    m.Description = @"MTTR for Category 3 and above.";
    m.FormatString = @"#,0.00";
}

// ---- MTTR Cat4 Plus Days ----
{
    var name = @"MTTR Cat4 Plus Days";
    var expr = @"CALCULATE ( [MTTR Days], fact_reliability_event[category] >= 4 )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"02 MTBF and MTTR";
    m.Description = @"MTTR for Category 4 and above.";
    m.FormatString = @"#,0.00";
}

// ---- Downtime Rank ----
{
    var name = @"Downtime Rank";
    var expr = @"RANKX (
    ALLSELECTED ( fact_reliability_event[category_label] ),
    [Total Downtime Days],
    ,
    DESC
)";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"03 Pareto";
    m.Description = @"Rank of each category by total downtime.";
    m.FormatString = @"#,0";
}

// ---- Cumulative Downtime Days ----
{
    var name = @"Cumulative Downtime Days";
    var expr = @"VAR CurrentRank = [Downtime Rank]
RETURN
    SUMX (
        FILTER (
            ALLSELECTED ( fact_reliability_event[category_label] ),
            [Downtime Rank] <= CurrentRank
        ),
        [Total Downtime Days]
    )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"03 Pareto";
    m.Description = @"Running total for the Pareto line.";
    m.FormatString = @"#,0.0";
}

// ---- Cumulative Downtime Pct ----
{
    var name = @"Cumulative Downtime Pct";
    var expr = @"DIVIDE (
    [Cumulative Downtime Days],
    CALCULATE (
        [Total Downtime Days],
        ALLSELECTED ( fact_reliability_event[category_label] )
    )
)";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"03 Pareto";
    m.Description = @"Cumulative percentage for the Pareto line.";
    m.FormatString = @"0.0%";
}

// ---- Severe Share of Downtime ----
{
    var name = @"Severe Share of Downtime";
    var expr = @"DIVIDE (
    CALCULATE ( [Total Downtime Days], fact_reliability_event[category] >= 3 ),
    CALCULATE ( [Total Downtime Days], ALL ( fact_reliability_event[category] ) )
)";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"03 Pareto";
    m.Description = @"Share of all downtime from Category 3 and above.";
    m.FormatString = @"0.0%";
}

// ---- Severe Share of Events ----
{
    var name = @"Severe Share of Events";
    var expr = @"DIVIDE (
    [Severe Event Count],
    CALCULATE ( [Event Count], ALL ( fact_reliability_event[category] ) )
)";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"03 Pareto";
    m.Description = @"Share of events that are severe. Contrast with the downtime share to show the Pareto effect.";
    m.FormatString = @"0.0%";
}

// ---- Pareto Statement ----
{
    var name = @"Pareto Statement";
    var expr = @"""Category 3 and above: "" & FORMAT ( [Severe Share of Events], ""0%"" )
    & "" of events, "" & FORMAT ( [Severe Share of Downtime], ""0%"" )
    & "" of downtime""";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"03 Pareto";
    m.Description = @"One-line summary for a card.";
}

// ---- Scenario Weighted Severity ----
{
    var name = @"Scenario Weighted Severity";
    var expr = @"VAR Cat = SELECTEDVALUE ( 'Scenario Category'[Category], 3 )
VAR Km = SELECTEDVALUE ( 'Scenario Distance'[Km], 100 )
RETURN
    Cat * EXP ( - DIVIDE ( Km, [Proximity Decay Km] ) )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"04 Scenario";
    m.Description = @"Category weighted by proximity, matching the regression input.";
    m.FormatString = @"#,0.00";
}

// ---- Expected Loss Mt ----
{
    var name = @"Expected Loss Mt";
    var expr = @"ABS ( [Severity Coefficient] ) * [Scenario Weighted Severity]";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"04 Scenario";
    m.Description = @"Central estimate of production lost.";
    m.FormatString = @"#,0.0";
}

// ---- Expected Loss Low Mt ----
{
    var name = @"Expected Loss Low Mt";
    var expr = @"ABS ( [Severity CI High] ) * [Scenario Weighted Severity]";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"04 Scenario";
    m.Description = @"Lower bound. Never display without this.";
    m.FormatString = @"#,0.0";
}

// ---- Expected Loss High Mt ----
{
    var name = @"Expected Loss High Mt";
    var expr = @"ABS ( [Severity CI Low] ) * [Scenario Weighted Severity]";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"04 Scenario";
    m.Description = @"Upper bound. Never display without this.";
    m.FormatString = @"#,0.0";
}

// ---- Daily Capability Mt ----
{
    var name = @"Daily Capability Mt";
    var expr = @"AVERAGE ( fact_reliability_monthly[daily_capability_mt] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"04 Scenario";
    m.Description = @"Mean daily throughput capability, converts tonnes to days.";
    m.FormatString = @"#,0.00";
}

// ---- Expected Downtime Days ----
{
    var name = @"Expected Downtime Days";
    var expr = @"DIVIDE ( [Expected Loss Mt], [Daily Capability Mt] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"04 Scenario";
    m.Description = @"Loss as days of normal throughput.";
    m.FormatString = @"#,0.0";
}

// ---- Value At Risk AUD ----
{
    var name = @"Value At Risk AUD";
    var expr = @"VAR PriceUSD = SELECTEDVALUE ( 'Iron Ore Price'[USD per tonne], 100 )
RETURN
    [Expected Loss Mt] * 1000000 * PriceUSD / [AUD per USD]";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"04 Scenario";
    m.Description = @"Deferred shipment value. Price and exchange rate are assumptions.";
    m.FormatString = @"\$#,0;(\$#,0)";
}

// ---- Loss Statement ----
{
    var name = @"Loss Statement";
    var expr = @"""Estimated "" & FORMAT ( [Expected Loss Mt], ""0.0"" ) & "" Mt lost, range ""
    & FORMAT ( [Expected Loss Low Mt], ""0.0"" ) & "" to ""
    & FORMAT ( [Expected Loss High Mt], ""0.0"" ) & "" Mt. About ""
    & FORMAT ( [Expected Downtime Days], ""0.0"" ) & "" days of throughput.""";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"04 Scenario";
    m.Description = @"Card text. Keeps the range attached to the central estimate.";
}

// ---- Nearest Analogue ----
{
    var name = @"Nearest Analogue";
    var expr = @"VAR Cat = SELECTEDVALUE ( 'Scenario Category'[Category], 3 )
VAR Km = SELECTEDVALUE ( 'Scenario Distance'[Km], 100 )
VAR Ranked =
    ADDCOLUMNS (
        ALL ( fact_reliability_event ),
        ""@dist"",
            ABS ( fact_reliability_event[category] - Cat ) * 100
                + ABS ( fact_reliability_event[km_to_port_hedland] - Km )
    )
VAR Best = TOPN ( 1, Ranked, [@dist], ASC )
RETURN
    CONCATENATEX ( Best, fact_reliability_event[event_label] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"04 Scenario";
    m.Description = @"Closest historical event to the scenario. Operators trust a named past event more than a modelled number.";
}

// ---- Analogue Actual Loss Mt ----
{
    var name = @"Analogue Actual Loss Mt";
    var expr = @"VAR Cat = SELECTEDVALUE ( 'Scenario Category'[Category], 3 )
VAR Km = SELECTEDVALUE ( 'Scenario Distance'[Km], 100 )
VAR Ranked =
    ADDCOLUMNS (
        ALL ( fact_reliability_event ),
        ""@dist"",
            ABS ( fact_reliability_event[category] - Cat ) * 100
                + ABS ( fact_reliability_event[km_to_port_hedland] - Km )
    )
VAR Best = TOPN ( 1, Ranked, [@dist], ASC )
RETURN
    MAXX ( Best, fact_reliability_event[event_lost_mt] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"04 Scenario";
    m.Description = @"What the nearest analogue actually cost. Sits beside the modelled estimate as a reality check.";
    m.FormatString = @"#,0.00";
}

// ---- Production Forgone AUD ----
{
    var name = @"Production Forgone AUD";
    var expr = @"VAR t = SELECTEDVALUE ( 'Lead Hours'[Hours] )
VAR PriceUSD = SELECTEDVALUE ( 'Iron Ore Price'[USD per tonne], 100 )
RETURN
    t * DIVIDE ( [Daily Capability Mt], 24 ) * 1000000 * PriceUSD
        / [AUD per USD]";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"05 Shutdown timing";
    m.Description = @"Cost of stopping early. Derived from measured throughput.";
    m.FormatString = @"\$#,0";
}

// ---- Damage Probability ----
{
    var name = @"Damage Probability";
    var expr = @"VAR t = SELECTEDVALUE ( 'Lead Hours'[Hours] )
VAR Cat = SELECTEDVALUE ( 'Scenario Category'[Category], 3 )
VAR Mult = SELECTEDVALUE ( 'Curve Sensitivity'[Multiplier], 1 )
VAR k = DIVIDE ( 0.06, MAX ( Cat, 1 ) ) * Mult
VAR mid = 12 * Cat
RETURN
    DIVIDE ( 1, 1 + EXP ( k * ( t - mid ) ) )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"05 Shutdown timing";
    m.Description = @"ASSUMPTION, not fitted. No operator publishes incident-level damage outcomes. Structured so a fitted curve can replace it.";
    m.FormatString = @"0.0%";
}

// ---- Expected Damage Cost AUD ----
{
    var name = @"Expected Damage Cost AUD";
    var expr = @"VAR Cat = SELECTEDVALUE ( 'Scenario Category'[Category], 3 )
VAR DamageCostPerCat = 50000000
RETURN
    [Damage Probability] * DamageCostPerCat * Cat";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"05 Shutdown timing";
    m.Description = @"Damage cost per category is an assumption, stated on the page.";
    m.FormatString = @"\$#,0";
}

// ---- Total Expected Cost AUD ----
{
    var name = @"Total Expected Cost AUD";
    var expr = @"[Production Forgone AUD] + [Expected Damage Cost AUD]";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"05 Shutdown timing";
    m.Description = @"The curve to minimise.";
    m.FormatString = @"\$#,0";
}

// ---- WHS Minimum Hours ----
{
    var name = @"WHS Minimum Hours";
    var expr = @"VAR Cat = SELECTEDVALUE ( 'Scenario Category'[Category], 3 )
RETURN
    IF ( Cat >= 3, 72, 48 )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"05 Shutdown timing";
    m.Description = @"Minimum safe evacuation window. A hard constraint, not a cost. Below this the option does not exist at any price.";
    m.FormatString = @"#,0";
}

// ---- Cost Within WHS Limit ----
{
    var name = @"Cost Within WHS Limit";
    var expr = @"IF (
    SELECTEDVALUE ( 'Lead Hours'[Hours] ) >= [WHS Minimum Hours],
    [Total Expected Cost AUD]
)";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"05 Shutdown timing";
    m.Description = @"Total cost, blanked inside the forbidden window.";
    m.FormatString = @"\$#,0";
}

// ---- Optimal Lead Hours ----
{
    var name = @"Optimal Lead Hours";
    var expr = @"VAR Costs =
    ADDCOLUMNS (
        FILTER ( ALL ( 'Lead Hours' ), 'Lead Hours'[Hours] >= [WHS Minimum Hours] ),
        ""@cost"", [Total Expected Cost AUD]
    )
VAR Best = TOPN ( 1, Costs, [@cost], ASC )
RETURN
    MAXX ( Best, 'Lead Hours'[Hours] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"05 Shutdown timing";
    m.Description = @"Lowest-cost lead time inside the safe window.";
    m.FormatString = @"#,0";
}

// ---- Optimal Statement ----
{
    var name = @"Optimal Statement";
    var expr = @"""Recommended shutdown: "" & FORMAT ( [Optimal Lead Hours], ""0"" )
    & "" hours before landfall. WH&S minimum is ""
    & FORMAT ( [WHS Minimum Hours], ""0"" ) & "" hours.""";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"05 Shutdown timing";
    m.Description = @"Card text for the recommendation.";
}

// ---- Actual Mt ----
{
    var name = @"Actual Mt";
    var expr = @"SUM ( fact_reliability_monthly[total_throughput_mt] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"06 Validation";
    m.Description = @"Observed throughput.";
    m.FormatString = @"#,0.0";
}

// ---- Fitted Mt ----
{
    var name = @"Fitted Mt";
    var expr = @"SUM ( fact_reliability_monthly[fitted_mt] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"06 Validation";
    m.Description = @"Model prediction with observed severity.";
    m.FormatString = @"#,0.0";
}

// ---- Capability Mt ----
{
    var name = @"Capability Mt";
    var expr = @"SUM ( fact_reliability_monthly[capability_mt] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"06 Validation";
    m.Description = @"Model prediction with severity set to zero.";
    m.FormatString = @"#,0.0";
}

// ---- Modelled Loss Mt ----
{
    var name = @"Modelled Loss Mt";
    var expr = @"SUM ( fact_reliability_monthly[lost_mt] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"06 Validation";
    m.Description = @"Capability minus fitted. Not capability minus actual: the gap between actual and fitted is ordinary model residual.";
    m.FormatString = @"#,0.0";
}

// ---- Residual Mt ----
{
    var name = @"Residual Mt";
    var expr = @"[Actual Mt] - [Fitted Mt]";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"06 Validation";
    m.Description = @"Model error, unrelated to cyclones.";
    m.FormatString = @"#,0.0";
}

// ---- Mean Absolute Error Mt ----
{
    var name = @"Mean Absolute Error Mt";
    var expr = @"AVERAGEX (
    fact_reliability_monthly,
    ABS (
        fact_reliability_monthly[total_throughput_mt]
            - fact_reliability_monthly[fitted_mt]
    )
)";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"06 Validation";
    m.Description = @"Average absolute model error.";
    m.FormatString = @"#,0.00";
}

// ---- Implied Closure Days ----
{
    var name = @"Implied Closure Days";
    var expr = @"DIVIDE ( [Total Lost Mt], [Daily Capability Mt] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"06 Validation";
    m.Description = @"Loss converted to days. The model never sees closure durations, so agreement with observed practice is external corroboration.";
    m.FormatString = @"#,0.0";
}

// ---- Return Period Years ----
{
    var name = @"Return Period Years";
    var expr = @"AVERAGE ( dim_return_period[return_period_years] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"07 Return periods";
    m.Description = @"Years between events of at least the selected severity and proximity.";
    m.FormatString = @"#,0.0";
}

// ---- Events Per Year ----
{
    var name = @"Events Per Year";
    var expr = @"AVERAGE ( dim_return_period[events_per_year] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"07 Return periods";
    m.Description = @"Poisson rate for the selected severity and proximity.";
    m.FormatString = @"#,0.000";
}

// ---- Season Probability ----
{
    var name = @"Season Probability";
    var expr = @"AVERAGE ( dim_return_period[prob_at_least_one_per_year] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"07 Return periods";
    m.Description = @"Chance of at least one such event in any given season.";
    m.FormatString = @"0.0%";
}

// ---- Return Period Statement ----
{
    var name = @"Return Period Statement";
    var expr = @"VAR RP = [Return Period Years]
VAR P = [Season Probability]
RETURN
    IF (
        ISBLANK ( RP ),
        ""Not observed in the record"",
        ""About once every "" & FORMAT ( RP, ""0.0"" ) & "" years, ""
            & FORMAT ( P, ""0%"" ) & "" chance in any season""
    )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"07 Return periods";
    m.Description = @"Plain-English card text. Handles the not-observed case rather than showing a blank.";
}

// ---- Expected Events Next Decade ----
{
    var name = @"Expected Events Next Decade";
    var expr = @"[Events Per Year] * 10";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"07 Return periods";
    m.Description = @"Planning horizon figure. Easier to act on than a return period.";
    m.FormatString = @"#,0.0";
}

// ---- Return Period Sample Size ----
{
    var name = @"Return Period Sample Size";
    var expr = @"SUM ( dim_return_period[events] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"07 Return periods";
    m.Description = @"Events the return period rests on. Show it: a 5.7 year figure built on two observations should be read as indicative.";
    m.FormatString = @"#,0";
}

// ---- Season Downtime Days ----
{
    var name = @"Season Downtime Days";
    var expr = @"CALCULATE (
    [Total Downtime Days],
    ALLEXCEPT ( fact_reliability_event, fact_reliability_event[season_label] )
)";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"08 Time";
    m.Description = @"Downtime by cyclone season. The season runs November to April, so a calendar year split would cut every season in half.";
    m.FormatString = @"#,0.0";
}

// ---- Worst Season Days ----
{
    var name = @"Worst Season Days";
    var expr = @"MAXX (
    VALUES ( fact_reliability_event[season_label] ),
    [Season Downtime Days]
)";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"08 Time";
    m.Description = @"Worst season on record.";
    m.FormatString = @"#,0.0";
}

// ---- Worst Season Label ----
{
    var name = @"Worst Season Label";
    var expr = @"VAR Ranked =
    ADDCOLUMNS (
        VALUES ( fact_reliability_event[season_label] ),
        ""@days"", [Season Downtime Days]
    )
VAR Best = TOPN ( 1, Ranked, [@days], DESC )
RETURN
    CONCATENATEX ( Best, fact_reliability_event[season_label] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"08 Time";
    m.Description = @"Which season was worst.";
}

// ---- Availability Rolling 12 ----
{
    var name = @"Availability Rolling 12";
    var expr = @"VAR LastMonth = MAX ( fact_reliability_monthly[month] )
RETURN
    CALCULATE (
        [Availability Pct],
        FILTER (
            ALL ( fact_reliability_monthly ),
            fact_reliability_monthly[month] <= LastMonth
                && fact_reliability_monthly[month] > EDATE ( LastMonth, -12 )
        )
    )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"08 Time";
    m.Description = @"Twelve-month rolling availability. Smooths the seasonal sawtooth.";
    m.FormatString = @"0.00%";
}

// ---- Downtime Days Rolling 12 ----
{
    var name = @"Downtime Days Rolling 12";
    var expr = @"VAR LastMonth = MAX ( fact_reliability_monthly[month] )
RETURN
    CALCULATE (
        [Total Downtime Days],
        FILTER (
            ALL ( fact_reliability_event ),
            fact_reliability_event[month] <= LastMonth
                && fact_reliability_event[month] > EDATE ( LastMonth, -12 )
        )
    )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"08 Time";
    m.Description = @"Rolling twelve-month downtime.";
    m.FormatString = @"#,0.0";
}

// ---- Availability Colour ----
{
    var name = @"Availability Colour";
    var expr = @"VAR A = [Availability Pct]
RETURN
    SWITCH (
        TRUE (),
        ISBLANK ( A ), ""#888780"",
        A >= [Availability Target], ""#1D9E75"",
        A >= 0.95, ""#EF9F27"",
        ""#E24B4A""
    )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"09 Formatting";
    m.Description = @"Feed to conditional formatting via Format > Fx > Field value.";
}

// ---- Severity Colour ----
{
    var name = @"Severity Colour";
    var expr = @"VAR C = SELECTEDVALUE ( fact_reliability_event[category] )
RETURN
    SWITCH (
        TRUE (),
        C >= 4, ""#A32D2D"",
        C = 3, ""#BA7517"",
        C >= 1, ""#378ADD"",
        ""#888780""
    )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"09 Formatting";
    m.Description = @"Category colour for charts. Pair with a shape or pattern so colour is not the only cue.";
}

// ---- Page Title ----
{
    var name = @"Page Title";
    var expr = @"VAR Cat = SELECTEDVALUE ( 'Scenario Category'[Category] )
VAR Km = SELECTEDVALUE ( 'Scenario Distance'[Km] )
RETURN
    IF (
        ISBLANK ( Cat ) || ISBLANK ( Km ),
        ""Select a scenario"",
        ""Category "" & Cat & "" at "" & Km & "" km from Port Hedland""
    )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"09 Formatting";
    m.Description = @"Dynamic title so a screenshot always shows which scenario is set.";
}

// ---- Row Count Check ----
{
    var name = @"Row Count Check";
    var expr = @"""Months: "" & DISTINCTCOUNT ( fact_reliability_monthly[month] )
    & ""   Events: "" & [Event Count]
    & ""   Period: "" & FORMAT ( MIN ( fact_reliability_monthly[month] ), ""mmm yyyy"" )
    & "" to "" & FORMAT ( MAX ( fact_reliability_monthly[month] ), ""mmm yyyy"" )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"09 Formatting";
    m.Description = @"Small footer text. Makes a silently applied filter obvious.";
}

// ---- Provenance Footer ----
{
    var name = @"Provenance Footer";
    var expr = @"""Model calibrated on Port of Port Hedland, ""
    & FORMAT ( MIN ( fact_reliability_monthly[month] ), ""yyyy"" ) & "" to ""
    & FORMAT ( MAX ( fact_reliability_monthly[month] ), ""yyyy"" )
    & "", against Bureau of Meteorology cyclone records. ""
    & ""Rio Tinto exports through Dampier and Cape Lambert, not Port Hedland.""";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"09 Formatting";
    m.Description = @"Footer for every page. States the main limitation before anyone has to ask.";
}

// ---- Defects Found ----
{
    var name = @"Defects Found";
    var expr = @"COUNTROWS ( dim_data_quality )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"10 Data quality";
    m.Description = @"Data quality issues identified.";
    m.FormatString = @"#,0";
}

// ---- Defects Fixed ----
{
    var name = @"Defects Fixed";
    var expr = @"CALCULATE (
    COUNTROWS ( dim_data_quality ),
    dim_data_quality[status] = ""Fixed""
)";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"10 Data quality";
    m.Description = @"Issues corrected rather than accepted.";
    m.FormatString = @"#,0";
}

// ---- High Severity Defects ----
{
    var name = @"High Severity Defects";
    var expr = @"CALCULATE (
    COUNTROWS ( dim_data_quality ),
    dim_data_quality[severity] = ""High""
)";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"10 Data quality";
    m.Description = @"Defects that would have changed the conclusions if missed.";
    m.FormatString = @"#,0";
}

// ---- Records Affected ----
{
    var name = @"Records Affected";
    var expr = @"SUM ( dim_data_quality[records_affected] )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"10 Data quality";
    m.Description = @"Records touched by a defect.";
    m.FormatString = @"#,0";
}

// ---- Parse Success Rate ----
{
    var name = @"Parse Success Rate";
    var expr = @"VAR Parsed =
    CALCULATE (
        COUNTROWS ( fact_reliability_monthly ),
        NOT ISBLANK ( fact_reliability_monthly[total_throughput_mt] )
    )
VAR Total = COUNTROWS ( ALL ( fact_reliability_monthly ) )
RETURN
    DIVIDE ( Parsed, Total )";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"10 Data quality";
    m.Description = @"Share of source PDFs parsed automatically.";
    m.FormatString = @"0.0%";
}

// ---- Data Quality Statement ----
{
    var name = @"Data Quality Statement";
    var expr = @"FORMAT ( [Defects Found], ""0"" ) & "" data quality issues found, ""
    & FORMAT ( [Defects Fixed], ""0"" ) & "" corrected. ""
    & FORMAT ( [High Severity Defects], ""0"" )
    & "" would have changed the conclusions.""";
    var m = tbl.Measures.FirstOrDefault(x => x.Name == name);
    if (m == null) { m = tbl.AddMeasure(name); created++; }
    else { updated++; }
    m.Expression = expr;
    m.DisplayFolder = @"10 Data quality";
    m.Description = @"Summary card text for page 5.";
}

Info("Measures created: " + created + ", updated: " + updated);